#pragma once

/**
 * @details Init specific ERRORS
 */
#define MYSTACK_ERROR_STACK_INIT_ELEMS_NULLPTR 1
#define MYSTACK_ERROR_STACK_INIT_MUTEX_NULLPTR 2
#define MYSTACK_ERROR_STACK_INIT_MUTEX_INIT_FAIL 3
#define MYSTACK_ERROR_STACK_INIT_FULL_NULLPTR 4
#define MYSTACK_ERROR_STACK_INIT_FULL_INIT_FAIL 5
#define MYSTACK_ERROR_STACK_INIT_EMPTY_NULLPTR 6
#define MYSTACK_ERROR_STACK_INIT_EMPTY_INIT_FAIL 7

/**
 * @details Destroy specific ERRORS
 */
#define MYSTACK_ERROR_STACK_DESTROY_MUTEX_DESTROY 1
#define MYSTACK_ERROR_STACK_DESTROY_FULL_CLOSE 2
#define MYSTACK_ERROR_STACK_DESTROY_EMPTY_CLOSE 3

/**
 * @details Pop specific ERRORS
 */

#define MYSTACK_ERROR_STACK_POP_DIFFERENT_TYPES 1
#define MYSTACK_ERROR_STACK_POP_FULL_WAIT_FAIL 2
#define MYSTACK_ERROR_STACK_POP_MUTEX_LOCK_FAIL 3
#define MYSTACK_ERROR_STACK_POP_MUTEX_UNLOCK_FAIL 4
#define MYSTACK_ERROR_STACK_POP_EMPTY_POST_FAIL 5

/**
 * @details Push specific ERRORS
 */
#define MYSTACK_ERROR_STACK_PUSH_DIFFERENT_TYPES 1
#define MYSTACK_ERROR_STACK_PUSH_EMPTY_WAIT_FAIL 2
#define MYSTACK_ERROR_STACK_PUSH_MUTEX_LOCK_FAIL 3
#define MYSTACK_ERROR_STACK_PUSH_MUTEX_UNLOCK_FAIL 4
#define MYSTACK_ERROR_STACK_PUSH_FULL_POST_FAIL 5